{
 "title": "ScaleIO",
 "description": "Data comes from Influx",
 "tags": [
  "ScaleIO",
  "Storage"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Pool",
    "query": "SHOW TAG VALUES FROM scaleio WITH KEY = Pool"
   }
  ]
 },
 "panels": [
  { "title": "Storage Pool $Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Pool" },
  {
   "title": "Workload Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "KBs", "label": "Throughput" }
   ],
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "query": "SELECT mean(\"value\") FROM \"scaleio\" WHERE \"Pool\" =~ /$Pool$/ AND \"type_instance\" = 'userDataReadBWC' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "totalReadBwc_thruKB" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "query": "SELECT mean(\"value\") FROM \"scaleio\" WHERE \"Pool\" =~ /$Pool$/ AND \"type_instance\" = 'userDataWriteBWC' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "totalWriteBwc_thruKB" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Workload IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "iops", "label": "Throughput" }
   ],
   "targets": [
    {
     "alias": "Read IOPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "query": "SELECT mean(\"value\") FROM \"scaleio\" WHERE \"Pool\" =~ /$Pool$/ AND \"type_instance\" = 'userDataReadBWC' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "totalReadBwc_IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    },
    {
     "alias": "Write IOPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "query": "SELECT mean(\"value\") FROM \"scaleio\" WHERE \"Pool\" =~ /$Pool$/ AND \"type_instance\" = 'userDataWriteBWC' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "totalWriteBwc_IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Flash Cache performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "rfCacheRead",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "select": [
      [
       { "params": [ "rfacheReadHit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    },
    {
     "alias": "rfCacheReadMiss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "select": [
      [
       { "params": [ "rfcacheReadMiss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    },
    {
     "alias": "rfCacheWritesReceived",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "select": [
      [
       { "params": [ "rfcacheWritesReceived" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Real Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "Degraded",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "query": "SELECT mean(\"value\") FROM \"scaleio\" WHERE \"Pool\" =~ /$Pool$/ AND \"type_instance\" = 'degradedHealthyCapacityInKb' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "degradedHealthyCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    },
    {
     "alias": "Unreachable",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "query": "SELECT mean(\"value\") FROM \"scaleio\" WHERE \"Pool\" =~ /$Pool$/ AND \"type_instance\" = 'unreachableUnusedCapacityInKb' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "unusedCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "query": "SELECT mean(\"value\") FROM \"scaleio\" WHERE \"Pool\" =~ /$Pool$/ AND \"type_instance\" = 'capacityInUseInKb' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "spareCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    },
    {
     "alias": "Allocated",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "query": "SELECT mean(\"value\") FROM \"scaleio\" WHERE \"Pool\" =~ /$Pool$/ AND \"type_instance\" = 'thinCapacityAllocatedInKb' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "thinCapacityAllocatedInKm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    },
    {
     "alias": "Useable",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "query": "SELECT mean(\"value\") FROM \"scaleio\" WHERE \"Pool\" =~ /$Pool$/ AND \"type_instance\" = 'availableForThickAllocationInKb' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "capacityAvailableForVolumeAllocationInKb"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Pool", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Rebuild/Rebalance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "iops", "label": "Throughput" }
   ],
   "targets": [
    {
     "alias": "Rebuild Read IOPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "select": [
      [
       { "params": [ "bckRebuildReadBwc_IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Rebuild Write IOPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "select": [
      [
       { "params": [ "bckRebuildWriteBwc_IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary vs Secondary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Primary Reads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "select": [
      [
       { "params": [ "primaryReadBWC_IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Primary Writes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "select": [
      [
       { "params": [ "primaryWriteBwc_IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Secondary Reads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "select": [
      [
       { "params": [ "SecondaryReadBwc_IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Secondary Writes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio",
     "select": [
      [
       { "params": [ "secondaryWriteBwc_IOPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}